import type { Metadata } from "next";
import Header from "@/components/Header";

import "@xyflow/react/dist/style.css";
import "@/theme/globals.css";
import Providers from "@/providers";
import localFont from "next/font/local";

const inter = localFont({
  src: "./inter-variable.ttf",
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`} data-vaul-drawer-wrapper="">
        <Providers>
          <Header />
          <div className="flex min-h-dvh flex-col justify-between">
            <main className="w-full max-w-[2560px] flex-grow self-center px-4 pb-6 pt-[86px] md:px-6">{children}</main>
            {/* <Footer /> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
