import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/theme/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Header />
        <div className="flex min-h-dvh flex-col justify-between">
          <main className="w-full flex-grow px-[22px] pb-[22px] pt-[86px]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
