import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "@xyflow/react/dist/style.css";
import "@/theme/globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Header />
        <div className="flex min-h-dvh flex-col justify-between">
          <main className="w-full flex-grow px-[14px] pb-[14px] pt-[86px] md:px-[22px] md:pb-[22px]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
